# Generated by Django 3.1.7 on 2021-04-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='watchedlistings', to='auctions.Listing'),
        ),
    ]
