# Generated by Django 3.2 on 2021-04-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210408_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought',
            name='winner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='auctions.user'),
            preserve_default=False,
        ),
    ]
